# Generated by Django 6.0.1 on 2026-02-13 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calendar_id', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'calendar_id')},
            },
        ),
        migrations.CreateModel(
            name='TogglOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggl_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toggl Organization',
                'ordering': ['name'],
                'unique_together': {('user', 'toggl_id')},
            },
        ),
        migrations.CreateModel(
            name='TogglWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('webhook_token', models.CharField(blank=True, help_text='Unique token for webhook URL routing', max_length=64, null=True, unique=True)),
                ('webhook_subscription_id', models.BigIntegerField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workspaces', to='sync.togglorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggl_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toggl Workspace',
                'ordering': ['name'],
                'unique_together': {('user', 'toggl_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_api_token', models.CharField(blank=True, default='', help_text='Toggl Token', max_length=255)),
                ('gauth_credentials_json', models.TextField(blank=True, default='', help_text='Google OAuth')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('last_toggl_metadata_sync', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credentials',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='EntityToCalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('tag', 'Tag'), ('project', 'Project'), ('workspace', 'Workspace'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(help_text='for display', max_length=255)),
                ('process_order', models.IntegerField(help_text='lower = prior', unique=True)),
                ('color_name', models.CharField(choices=[('Lavender', '#a4bdfc'), ('Sage', '#7ae7bf'), ('Grape', '#dbadff'), ('Flamingo', '#ff887c'), ('Banana', '#fbd75b'), ('Tangerine', '#ffb878'), ('Peacock', '#46d6db'), ('Graphite', '#e1e1e1'), ('Blueberry', '#5484ed'), ('Basil', '#51b749'), ('Tomato', '#dc2127')], default='Lavender', help_text='Color for calendar events', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_mappings', to=settings.AUTH_USER_MODEL)),
                ('gcal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='sync.googlecal')),
            ],
            options={
                'verbose_name': 'Mapping',
                'verbose_name_plural': 'Mappings',
                'ordering': ['entity_type', 'process_order', 'entity_name'],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='TogglTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_id', models.BigIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.BigIntegerField(blank=True, null=True)),
                ('tag_ids', models.JSONField(default=list)),
                ('synced', models.BooleanField(default=False)),
                ('pending_deletion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='synced_entries', to='sync.googlecal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toggl Entry',
                'verbose_name_plural': 'Toggl Entries',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'synced', 'updated_at'], name='sync_togglt_user_id_655dd0_idx')],
                'unique_together': {('user', 'toggl_id')},
            },
        ),
        migrations.CreateModel(
            name='TogglTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggl_tags', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='sync.togglworkspace')),
            ],
            options={
                'verbose_name': 'Toggl Tag',
                'ordering': ['name'],
                'unique_together': {('user', 'toggl_id')},
            },
        ),
        migrations.CreateModel(
            name='TogglProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggl_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggl_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='sync.togglworkspace')),
            ],
            options={
                'verbose_name': 'Toggl Project',
                'ordering': ['name'],
                'unique_together': {('user', 'toggl_id')},
            },
        ),
    ]
