# Generated by Django 6.0.2 on 2026-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='googlecal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='googlecal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toggltimeentry',
            name='calendar',
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='Auto-created Toggl calendar ID', max_length=255),
        ),
        migrations.DeleteModel(
            name='EntityToCalMapping',
        ),
        migrations.DeleteModel(
            name='GoogleCal',
        ),
    ]
