# Generated by Django 6.0.2 on 2026-02-22 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_googlecal_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('tag', 'Tag'), ('project', 'Project'), ('workspace', 'Workspace'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(help_text='for display', max_length=255)),
                ('process_order', models.IntegerField(help_text='lower = higher priority', unique=True)),
                ('color_name', models.CharField(choices=[('Lavender', '#a4bdfc'), ('Sage', '#7ae7bf'), ('Grape', '#dbadff'), ('Flamingo', '#ff887c'), ('Banana', '#fbd75b'), ('Tangerine', '#ffb878'), ('Peacock', '#46d6db'), ('Graphite', '#e1e1e1'), ('Blueberry', '#5484ed'), ('Basil', '#51b749'), ('Tomato', '#dc2127')], default='Lavender', help_text='Color for calendar events', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color Mapping',
                'verbose_name_plural': 'Color Mappings',
                'ordering': ['process_order'],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
